//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientsWcf
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PersonDto : object
    {
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private System.Nullable<System.DateTime> DateGivingDocumentField;
        
        private string DocumentNumberField;
        
        private string DocumentSerieField;
        
        private string DocumentTypeField;
        
        private string FirstnameField;
        
        private string HowGiveDocumentField;
        
        private System.Guid IDField;
        
        private string LastnameField;
        
        private string PatronymicField;
        
        private int SexEnumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateGivingDocument
        {
            get
            {
                return this.DateGivingDocumentField;
            }
            set
            {
                this.DateGivingDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                this.DocumentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentSerie
        {
            get
            {
                return this.DocumentSerieField;
            }
            set
            {
                this.DocumentSerieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname
        {
            get
            {
                return this.FirstnameField;
            }
            set
            {
                this.FirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HowGiveDocument
        {
            get
            {
                return this.HowGiveDocumentField;
            }
            set
            {
                this.HowGiveDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this.LastnameField;
            }
            set
            {
                this.LastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SexEnum
        {
            get
            {
                return this.SexEnumField;
            }
            set
            {
                this.SexEnumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndicantDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class IndicantDto : object
    {
        
        private System.Nullable<System.DateTime> IndicantDateTimeField;
        
        private string IndicantNameField;
        
        private string IndicantStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IndicantDateTime
        {
            get
            {
                return this.IndicantDateTimeField;
            }
            set
            {
                this.IndicantDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicantName
        {
            get
            {
                return this.IndicantNameField;
            }
            set
            {
                this.IndicantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicantString
        {
            get
            {
                return this.IndicantStringField;
            }
            set
            {
                this.IndicantStringField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientsWcf.IInpatientDoctor")]
    public interface IInpatientDoctor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetPersons", ReplyAction="http://tempuri.org/IInpatientDoctor/GetPersonsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.PersonDto>> GetPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetIndicant", ReplyAction="http://tempuri.org/IInpatientDoctor/GetIndicantResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetIndicantAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/Authorize", ReplyAction="http://tempuri.org/IInpatientDoctor/AuthorizeResponse")]
        System.Threading.Tasks.Task<bool> AuthorizeAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IInpatientDoctorChannel : PatientsWcf.IInpatientDoctor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InpatientDoctorClient : System.ServiceModel.ClientBase<PatientsWcf.IInpatientDoctor>, PatientsWcf.IInpatientDoctor
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InpatientDoctorClient() : 
                base(InpatientDoctorClient.GetDefaultBinding(), InpatientDoctorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IInpatientDoctor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), InpatientDoctorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.PersonDto>> GetPersonsAsync()
        {
            return base.Channel.GetPersonsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetIndicantAsync(System.Guid id)
        {
            return base.Channel.GetIndicantAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AuthorizeAsync(string login, string password)
        {
            return base.Channel.AuthorizeAsync(login, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInpatientDoctor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInpatientDoctor))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.120/Govno/");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InpatientDoctorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IInpatientDoctor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InpatientDoctorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IInpatientDoctor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IInpatientDoctor,
        }
    }
}
