//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientsWcf
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonQueryParamsDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PersonQueryParamsDto : object
    {
        
        private System.Collections.Generic.List<System.Guid> DepartmentListField;
        
        private System.Collections.Generic.List<string> PersonAttributeListField;
        
        private PatientsWcf.FilterPersonTypeDto PersonQueryTypeField;
        
        private System.Collections.Generic.List<PatientsWcf.PersonnelParamDto> PersonnelListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> DepartmentList
        {
            get
            {
                return this.DepartmentListField;
            }
            set
            {
                this.DepartmentListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PersonAttributeList
        {
            get
            {
                return this.PersonAttributeListField;
            }
            set
            {
                this.PersonAttributeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.FilterPersonTypeDto PersonQueryType
        {
            get
            {
                return this.PersonQueryTypeField;
            }
            set
            {
                this.PersonQueryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.PersonnelParamDto> PersonnelList
        {
            get
            {
                return this.PersonnelListField;
            }
            set
            {
                this.PersonnelListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterPersonTypeDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public enum FilterPersonTypeDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MyPatients = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InEmergencyRoom = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToMyDepartmentsInDay = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToMyDepartments = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByDoctor = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByDepartments = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllPatients = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonnelParamDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PersonnelParamDto : object
    {
        
        private System.Guid PersonIdField;
        
        private System.Guid PositionTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PositionTypeId
        {
            get
            {
                return this.PositionTypeIdField;
            }
            set
            {
                this.PositionTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PatientDto : object
    {
        
        private PatientsWcf.AdmissionInfoDto AdmissionInfoField;
        
        private int AgeField;
        
        private string AgeDescriptionField;
        
        private string BedField;
        
        private string BenefitsField;
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private string DiagnosField;
        
        private System.Guid DiagnosAnamnesisIDField;
        
        private string DoctorField;
        
        private string FirstnameField;
        
        private System.Guid HealthcareServiceIdField;
        
        private string HelpFormField;
        
        private bool InResuscitationField;
        
        private bool IsWorkingField;
        
        private string LastnameField;
        
        private System.Guid LifeAnamnesisIDField;
        
        private string ObservationModeField;
        
        private string ObservationTypeField;
        
        private System.Guid PathologyАnamnesisIDField;
        
        private string PatronymicField;
        
        private System.Guid PersonIDField;
        
        private System.Guid PersonnelIDField;
        
        private string PhysicalRestraintField;
        
        private string ResponsibleDepField;
        
        private string RoomField;
        
        private System.Nullable<System.DateTime> SDDepTreatmentCaseField;
        
        private System.Nullable<System.DateTime> SDInpatientServiceCaseField;
        
        private System.Nullable<System.DateTime> SDReceptionCaseField;
        
        private string ServiceCaseNumberField;
        
        private int SexEnumField;
        
        private string StayDepField;
        
        private System.Nullable<System.Guid> VersionIDField;
        
        private bool isChangedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.AdmissionInfoDto AdmissionInfo
        {
            get
            {
                return this.AdmissionInfoField;
            }
            set
            {
                this.AdmissionInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgeDescription
        {
            get
            {
                return this.AgeDescriptionField;
            }
            set
            {
                this.AgeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bed
        {
            get
            {
                return this.BedField;
            }
            set
            {
                this.BedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Benefits
        {
            get
            {
                return this.BenefitsField;
            }
            set
            {
                this.BenefitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnos
        {
            get
            {
                return this.DiagnosField;
            }
            set
            {
                this.DiagnosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DiagnosAnamnesisID
        {
            get
            {
                return this.DiagnosAnamnesisIDField;
            }
            set
            {
                this.DiagnosAnamnesisIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Doctor
        {
            get
            {
                return this.DoctorField;
            }
            set
            {
                this.DoctorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname
        {
            get
            {
                return this.FirstnameField;
            }
            set
            {
                this.FirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid HealthcareServiceId
        {
            get
            {
                return this.HealthcareServiceIdField;
            }
            set
            {
                this.HealthcareServiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HelpForm
        {
            get
            {
                return this.HelpFormField;
            }
            set
            {
                this.HelpFormField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InResuscitation
        {
            get
            {
                return this.InResuscitationField;
            }
            set
            {
                this.InResuscitationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWorking
        {
            get
            {
                return this.IsWorkingField;
            }
            set
            {
                this.IsWorkingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this.LastnameField;
            }
            set
            {
                this.LastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LifeAnamnesisID
        {
            get
            {
                return this.LifeAnamnesisIDField;
            }
            set
            {
                this.LifeAnamnesisIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservationMode
        {
            get
            {
                return this.ObservationModeField;
            }
            set
            {
                this.ObservationModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservationType
        {
            get
            {
                return this.ObservationTypeField;
            }
            set
            {
                this.ObservationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PathologyАnamnesisID
        {
            get
            {
                return this.PathologyАnamnesisIDField;
            }
            set
            {
                this.PathologyАnamnesisIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonID
        {
            get
            {
                return this.PersonIDField;
            }
            set
            {
                this.PersonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonnelID
        {
            get
            {
                return this.PersonnelIDField;
            }
            set
            {
                this.PersonnelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalRestraint
        {
            get
            {
                return this.PhysicalRestraintField;
            }
            set
            {
                this.PhysicalRestraintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsibleDep
        {
            get
            {
                return this.ResponsibleDepField;
            }
            set
            {
                this.ResponsibleDepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room
        {
            get
            {
                return this.RoomField;
            }
            set
            {
                this.RoomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SDDepTreatmentCase
        {
            get
            {
                return this.SDDepTreatmentCaseField;
            }
            set
            {
                this.SDDepTreatmentCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SDInpatientServiceCase
        {
            get
            {
                return this.SDInpatientServiceCaseField;
            }
            set
            {
                this.SDInpatientServiceCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SDReceptionCase
        {
            get
            {
                return this.SDReceptionCaseField;
            }
            set
            {
                this.SDReceptionCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCaseNumber
        {
            get
            {
                return this.ServiceCaseNumberField;
            }
            set
            {
                this.ServiceCaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SexEnum
        {
            get
            {
                return this.SexEnumField;
            }
            set
            {
                this.SexEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StayDep
        {
            get
            {
                return this.StayDepField;
            }
            set
            {
                this.StayDepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> VersionID
        {
            get
            {
                return this.VersionIDField;
            }
            set
            {
                this.VersionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isChanged
        {
            get
            {
                return this.isChangedField;
            }
            set
            {
                this.isChangedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdmissionInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class AdmissionInfoDto : object
    {
        
        private string DtcField;
        
        private string InpatientSrvField;
        
        private string ReceptCaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dtc
        {
            get
            {
                return this.DtcField;
            }
            set
            {
                this.DtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InpatientSrv
        {
            get
            {
                return this.InpatientSrvField;
            }
            set
            {
                this.InpatientSrvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceptCase
        {
            get
            {
                return this.ReceptCaseField;
            }
            set
            {
                this.ReceptCaseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndicantDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class IndicantDto : object
    {
        
        private System.Nullable<System.DateTime> IndicantDateTimeField;
        
        private string IndicantNameField;
        
        private string IndicantStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IndicantDateTime
        {
            get
            {
                return this.IndicantDateTimeField;
            }
            set
            {
                this.IndicantDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicantName
        {
            get
            {
                return this.IndicantNameField;
            }
            set
            {
                this.IndicantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicantString
        {
            get
            {
                return this.IndicantStringField;
            }
            set
            {
                this.IndicantStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualDoctorDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class ActualDoctorDto : object
    {
        
        private System.Nullable<System.DateTime> DateUpdateField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private string PatronymicField;
        
        private System.Guid PersonnelIdField;
        
        private string PersonnelNameField;
        
        private string SurNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonnelId
        {
            get
            {
                return this.PersonnelIdField;
            }
            set
            {
                this.PersonnelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonnelName
        {
            get
            {
                return this.PersonnelNameField;
            }
            set
            {
                this.PersonnelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class DepartmentDto : object
    {
        
        private System.Guid BusinessElementIDField;
        
        private string BusinessElementShortNameField;
        
        private System.Nullable<System.DateTime> DateUpdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BusinessElementID
        {
            get
            {
                return this.BusinessElementIDField;
            }
            set
            {
                this.BusinessElementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessElementShortName
        {
            get
            {
                return this.BusinessElementShortNameField;
            }
            set
            {
                this.BusinessElementShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class UserInfoDto : object
    {
        
        private System.Collections.Generic.List<PatientsWcf.DepartmentInfoDto> DepartmentInfoListField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MiddleNameField;
        
        private System.Collections.Generic.List<string> PermissionsField;
        
        private string SnilsField;
        
        private System.Guid UserIdAVField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.DepartmentInfoDto> DepartmentInfoList
        {
            get
            {
                return this.DepartmentInfoListField;
            }
            set
            {
                this.DepartmentInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Snils
        {
            get
            {
                return this.SnilsField;
            }
            set
            {
                this.SnilsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserIdAV
        {
            get
            {
                return this.UserIdAVField;
            }
            set
            {
                this.UserIdAVField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class DepartmentInfoDto : object
    {
        
        private System.Guid DepartmentIDField;
        
        private string DepartmentNameField;
        
        private string DepartmentShortNameField;
        
        private string PositionField;
        
        private System.Nullable<System.Guid> PositionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentShortName
        {
            get
            {
                return this.DepartmentShortNameField;
            }
            set
            {
                this.DepartmentShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PositionID
        {
            get
            {
                return this.PositionIDField;
            }
            set
            {
                this.PositionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class UserDto : object
    {
        
        private string DescriptionField;
        
        private string FIOField;
        
        private bool HasWebCustomizationField;
        
        private string LoginField;
        
        private System.Collections.Generic.List<PatientsWcf.UserDto> SubItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO
        {
            get
            {
                return this.FIOField;
            }
            set
            {
                this.FIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWebCustomization
        {
            get
            {
                return this.HasWebCustomizationField;
            }
            set
            {
                this.HasWebCustomizationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.UserDto> SubItems
        {
            get
            {
                return this.SubItemsField;
            }
            set
            {
                this.SubItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomizationInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomizationInfoDto : object
    {
        
        private string CustomSettingsField;
        
        private PatientsWcf.WebPageInfosDto PagesSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomSettings
        {
            get
            {
                return this.CustomSettingsField;
            }
            set
            {
                this.CustomSettingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.WebPageInfosDto PagesSettings
        {
            get
            {
                return this.PagesSettingsField;
            }
            set
            {
                this.PagesSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="WebPageInfosDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto", ItemName="WebPageInfoDto", KeyName="FormId", ValueName="FormSettings")]
    public class WebPageInfosDto : System.Collections.Generic.Dictionary<string, string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentPatientDiagnosInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class DepartmentPatientDiagnosInfoDto : object
    {
        
        private string DepartmentField;
        
        private System.Collections.Generic.List<PatientsWcf.PatientDiagnosInfoDto> PatientDiagnosInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.PatientDiagnosInfoDto> PatientDiagnosInfoList
        {
            get
            {
                return this.PatientDiagnosInfoListField;
            }
            set
            {
                this.PatientDiagnosInfoListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDiagnosInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PatientDiagnosInfoDto : object
    {
        
        private string AnamnesField;
        
        private string AnamnesConfigurationField;
        
        private string AnamnesDocumentFormatField;
        
        private string CureStagesDiagnosField;
        
        private string DiagnosFullPresentetionStringField;
        
        private string DiagnosTextField;
        
        private string DiagnosisAccuracyField;
        
        private string DiagnosisImportanceField;
        
        private System.Nullable<System.DateTime> HServicePlannedStartDateField;
        
        private System.Nullable<System.DateTime> HServicePrescribedStartDateField;
        
        private System.Nullable<System.DateTime> HServiceStartDateField;
        
        private string HealthcareServiceNameField;
        
        private System.Nullable<System.DateTime> HealthcareServiceSDField;
        
        private string IllnessTypeField;
        
        private string MKBDiagnosisCodeField;
        
        private string SeverityField;
        
        private System.Nullable<System.DateTime> WhenStartedDateField;
        
        private string WhoStartedStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anamnes
        {
            get
            {
                return this.AnamnesField;
            }
            set
            {
                this.AnamnesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnamnesConfiguration
        {
            get
            {
                return this.AnamnesConfigurationField;
            }
            set
            {
                this.AnamnesConfigurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnamnesDocumentFormat
        {
            get
            {
                return this.AnamnesDocumentFormatField;
            }
            set
            {
                this.AnamnesDocumentFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CureStagesDiagnos
        {
            get
            {
                return this.CureStagesDiagnosField;
            }
            set
            {
                this.CureStagesDiagnosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnosFullPresentetionString
        {
            get
            {
                return this.DiagnosFullPresentetionStringField;
            }
            set
            {
                this.DiagnosFullPresentetionStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnosText
        {
            get
            {
                return this.DiagnosTextField;
            }
            set
            {
                this.DiagnosTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnosisAccuracy
        {
            get
            {
                return this.DiagnosisAccuracyField;
            }
            set
            {
                this.DiagnosisAccuracyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnosisImportance
        {
            get
            {
                return this.DiagnosisImportanceField;
            }
            set
            {
                this.DiagnosisImportanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HServicePlannedStartDate
        {
            get
            {
                return this.HServicePlannedStartDateField;
            }
            set
            {
                this.HServicePlannedStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HServicePrescribedStartDate
        {
            get
            {
                return this.HServicePrescribedStartDateField;
            }
            set
            {
                this.HServicePrescribedStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HServiceStartDate
        {
            get
            {
                return this.HServiceStartDateField;
            }
            set
            {
                this.HServiceStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HealthcareServiceName
        {
            get
            {
                return this.HealthcareServiceNameField;
            }
            set
            {
                this.HealthcareServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HealthcareServiceSD
        {
            get
            {
                return this.HealthcareServiceSDField;
            }
            set
            {
                this.HealthcareServiceSDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IllnessType
        {
            get
            {
                return this.IllnessTypeField;
            }
            set
            {
                this.IllnessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MKBDiagnosisCode
        {
            get
            {
                return this.MKBDiagnosisCodeField;
            }
            set
            {
                this.MKBDiagnosisCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> WhenStartedDate
        {
            get
            {
                return this.WhenStartedDateField;
            }
            set
            {
                this.WhenStartedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoStartedString
        {
            get
            {
                return this.WhoStartedStringField;
            }
            set
            {
                this.WhoStartedStringField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientsWcf.IInpatientDoctor")]
    public interface IInpatientDoctor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetPatients", ReplyAction="http://tempuri.org/IInpatientDoctor/GetPatientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.PatientDto>> GetPatientsAsync(PatientsWcf.PersonQueryParamsDto personQueryParamsDto, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetIndicant", ReplyAction="http://tempuri.org/IInpatientDoctor/GetIndicantResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetIndicantAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/Authorize", ReplyAction="http://tempuri.org/IInpatientDoctor/AuthorizeResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.Guid>> AuthorizeAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetAllActualDoctors", ReplyAction="http://tempuri.org/IInpatientDoctor/GetAllActualDoctorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.ActualDoctorDto>> GetAllActualDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetAllDepartments", ReplyAction="http://tempuri.org/IInpatientDoctor/GetAllDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.DepartmentDto>> GetAllDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetUserInfo", ReplyAction="http://tempuri.org/IInpatientDoctor/GetUserInfoResponse")]
        System.Threading.Tasks.Task<PatientsWcf.UserInfoDto> GetUserInfoAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetAllUsers", ReplyAction="http://tempuri.org/IInpatientDoctor/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.UserDto>> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetCustomization", ReplyAction="http://tempuri.org/IInpatientDoctor/GetCustomizationResponse")]
        System.Threading.Tasks.Task<PatientsWcf.CustomizationInfoDto> GetCustomizationAsync(string login, string sourceLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/SaveCustomization", ReplyAction="http://tempuri.org/IInpatientDoctor/SaveCustomizationResponse")]
        System.Threading.Tasks.Task<bool> SaveCustomizationAsync(PatientsWcf.CustomizationInfoDto customInfoDto, string login, string targetLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/CopyCustomization", ReplyAction="http://tempuri.org/IInpatientDoctor/CopyCustomizationResponse")]
        System.Threading.Tasks.Task<bool> CopyCustomizationAsync(string sourceLogin, string targetLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetHealthcareIndicants", ReplyAction="http://tempuri.org/IInpatientDoctor/GetHealthcareIndicantsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetHealthcareIndicantsAsync(System.Guid id, double days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetPatientDiagnosis", ReplyAction="http://tempuri.org/IInpatientDoctor/GetPatientDiagnosisResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.DepartmentPatientDiagnosInfoDto>> GetPatientDiagnosisAsync(System.Guid patientId, System.Guid healthcareServiceId, bool isArchived);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IInpatientDoctorChannel : PatientsWcf.IInpatientDoctor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InpatientDoctorClient : System.ServiceModel.ClientBase<PatientsWcf.IInpatientDoctor>, PatientsWcf.IInpatientDoctor
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InpatientDoctorClient() : 
                base(InpatientDoctorClient.GetDefaultBinding(), InpatientDoctorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IInpatientDoctor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), InpatientDoctorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.PatientDto>> GetPatientsAsync(PatientsWcf.PersonQueryParamsDto personQueryParamsDto, string login)
        {
            return base.Channel.GetPatientsAsync(personQueryParamsDto, login);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetIndicantAsync(System.Guid id)
        {
            return base.Channel.GetIndicantAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.Guid>> AuthorizeAsync(string login, string password)
        {
            return base.Channel.AuthorizeAsync(login, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.ActualDoctorDto>> GetAllActualDoctorsAsync()
        {
            return base.Channel.GetAllActualDoctorsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.DepartmentDto>> GetAllDepartmentsAsync()
        {
            return base.Channel.GetAllDepartmentsAsync();
        }
        
        public System.Threading.Tasks.Task<PatientsWcf.UserInfoDto> GetUserInfoAsync(string login)
        {
            return base.Channel.GetUserInfoAsync(login);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.UserDto>> GetAllUsersAsync()
        {
            return base.Channel.GetAllUsersAsync();
        }
        
        public System.Threading.Tasks.Task<PatientsWcf.CustomizationInfoDto> GetCustomizationAsync(string login, string sourceLogin)
        {
            return base.Channel.GetCustomizationAsync(login, sourceLogin);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCustomizationAsync(PatientsWcf.CustomizationInfoDto customInfoDto, string login, string targetLogin)
        {
            return base.Channel.SaveCustomizationAsync(customInfoDto, login, targetLogin);
        }
        
        public System.Threading.Tasks.Task<bool> CopyCustomizationAsync(string sourceLogin, string targetLogin)
        {
            return base.Channel.CopyCustomizationAsync(sourceLogin, targetLogin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetHealthcareIndicantsAsync(System.Guid id, double days)
        {
            return base.Channel.GetHealthcareIndicantsAsync(id, days);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.DepartmentPatientDiagnosInfoDto>> GetPatientDiagnosisAsync(System.Guid patientId, System.Guid healthcareServiceId, bool isArchived)
        {
            return base.Channel.GetPatientDiagnosisAsync(patientId, healthcareServiceId, isArchived);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInpatientDoctor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInpatientDoctor))
            {
                return new System.ServiceModel.EndpointAddress("http://95.161.3.172:666/Doctest/");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InpatientDoctorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IInpatientDoctor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InpatientDoctorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IInpatientDoctor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IInpatientDoctor,
        }
    }
}
