//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientsWcf
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonQueryParamsDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PersonQueryParamsDto : object
    {
        
        private System.Collections.Generic.List<System.Guid> DepartmentListField;
        
        private System.Collections.Generic.List<string> PersonAttributeListField;
        
        private PatientsWcf.FilterPersonTypeDto PersonQueryTypeField;
        
        private System.Collections.Generic.List<PatientsWcf.PersonnelParamDto> PersonnelListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Guid> DepartmentList
        {
            get
            {
                return this.DepartmentListField;
            }
            set
            {
                this.DepartmentListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PersonAttributeList
        {
            get
            {
                return this.PersonAttributeListField;
            }
            set
            {
                this.PersonAttributeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.FilterPersonTypeDto PersonQueryType
        {
            get
            {
                return this.PersonQueryTypeField;
            }
            set
            {
                this.PersonQueryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.PersonnelParamDto> PersonnelList
        {
            get
            {
                return this.PersonnelListField;
            }
            set
            {
                this.PersonnelListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterPersonTypeDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public enum FilterPersonTypeDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MyPatients = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InEmergencyRoom = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToMyDepartmentsInDay = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToMyDepartments = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByDoctor = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByDepartments = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllPatients = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonnelParamDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PersonnelParamDto : object
    {
        
        private System.Guid PersonIdField;
        
        private System.Guid PositionTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PositionTypeId
        {
            get
            {
                return this.PositionTypeIdField;
            }
            set
            {
                this.PositionTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class PatientDto : object
    {
        
        private int AgeField;
        
        private string AgeDescriptionField;
        
        private string BedField;
        
        private System.Nullable<System.DateTime> BirthdayField;
        
        private string DiagnosField;
        
        private string DoctorField;
        
        private string FirstnameField;
        
        private bool InResuscitationField;
        
        private string LastnameField;
        
        private string ObservationModeField;
        
        private string ObservationTypeField;
        
        private string PatronymicField;
        
        private System.Guid PersonIDField;
        
        private string PhysicalRestraintField;
        
        private string ResponsibleDepField;
        
        private string RoomField;
        
        private System.Nullable<System.DateTime> SDDepTreatmentCaseField;
        
        private System.Nullable<System.DateTime> SDInpatientServiceCaseField;
        
        private string ServiceCaseNumberField;
        
        private int SexEnumField;
        
        private string StayDepField;
        
        private System.Nullable<System.Guid> VersionIDField;
        
        private bool isChangedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgeDescription
        {
            get
            {
                return this.AgeDescriptionField;
            }
            set
            {
                this.AgeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bed
        {
            get
            {
                return this.BedField;
            }
            set
            {
                this.BedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnos
        {
            get
            {
                return this.DiagnosField;
            }
            set
            {
                this.DiagnosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Doctor
        {
            get
            {
                return this.DoctorField;
            }
            set
            {
                this.DoctorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname
        {
            get
            {
                return this.FirstnameField;
            }
            set
            {
                this.FirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InResuscitation
        {
            get
            {
                return this.InResuscitationField;
            }
            set
            {
                this.InResuscitationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this.LastnameField;
            }
            set
            {
                this.LastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservationMode
        {
            get
            {
                return this.ObservationModeField;
            }
            set
            {
                this.ObservationModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservationType
        {
            get
            {
                return this.ObservationTypeField;
            }
            set
            {
                this.ObservationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonID
        {
            get
            {
                return this.PersonIDField;
            }
            set
            {
                this.PersonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalRestraint
        {
            get
            {
                return this.PhysicalRestraintField;
            }
            set
            {
                this.PhysicalRestraintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsibleDep
        {
            get
            {
                return this.ResponsibleDepField;
            }
            set
            {
                this.ResponsibleDepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room
        {
            get
            {
                return this.RoomField;
            }
            set
            {
                this.RoomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SDDepTreatmentCase
        {
            get
            {
                return this.SDDepTreatmentCaseField;
            }
            set
            {
                this.SDDepTreatmentCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SDInpatientServiceCase
        {
            get
            {
                return this.SDInpatientServiceCaseField;
            }
            set
            {
                this.SDInpatientServiceCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCaseNumber
        {
            get
            {
                return this.ServiceCaseNumberField;
            }
            set
            {
                this.ServiceCaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SexEnum
        {
            get
            {
                return this.SexEnumField;
            }
            set
            {
                this.SexEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StayDep
        {
            get
            {
                return this.StayDepField;
            }
            set
            {
                this.StayDepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> VersionID
        {
            get
            {
                return this.VersionIDField;
            }
            set
            {
                this.VersionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isChanged
        {
            get
            {
                return this.isChangedField;
            }
            set
            {
                this.isChangedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndicantDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class IndicantDto : object
    {
        
        private System.Nullable<System.DateTime> IndicantDateTimeField;
        
        private string IndicantNameField;
        
        private string IndicantStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IndicantDateTime
        {
            get
            {
                return this.IndicantDateTimeField;
            }
            set
            {
                this.IndicantDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicantName
        {
            get
            {
                return this.IndicantNameField;
            }
            set
            {
                this.IndicantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicantString
        {
            get
            {
                return this.IndicantStringField;
            }
            set
            {
                this.IndicantStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualDoctorDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class ActualDoctorDto : object
    {
        
        private System.Nullable<System.DateTime> DateUpdateField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private string PatronymicField;
        
        private System.Guid PersonnelIdField;
        
        private string PersonnelNameField;
        
        private string SurNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonnelId
        {
            get
            {
                return this.PersonnelIdField;
            }
            set
            {
                this.PersonnelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonnelName
        {
            get
            {
                return this.PersonnelNameField;
            }
            set
            {
                this.PersonnelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class DepartmentDto : object
    {
        
        private System.Guid BusinessElementIDField;
        
        private string BusinessElementShortNameField;
        
        private System.Nullable<System.DateTime> DateUpdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BusinessElementID
        {
            get
            {
                return this.BusinessElementIDField;
            }
            set
            {
                this.BusinessElementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessElementShortName
        {
            get
            {
                return this.BusinessElementShortNameField;
            }
            set
            {
                this.BusinessElementShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class UserInfoDto : object
    {
        
        private System.Collections.Generic.List<PatientsWcf.DepartmentInfoDto> DepartmentInfoListField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MiddleNameField;
        
        private System.Collections.Generic.List<string> PermissionsField;
        
        private string SnilsField;
        
        private System.Guid UserIdAVField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.DepartmentInfoDto> DepartmentInfoList
        {
            get
            {
                return this.DepartmentInfoListField;
            }
            set
            {
                this.DepartmentInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Snils
        {
            get
            {
                return this.SnilsField;
            }
            set
            {
                this.SnilsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserIdAV
        {
            get
            {
                return this.UserIdAVField;
            }
            set
            {
                this.UserIdAVField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class DepartmentInfoDto : object
    {
        
        private System.Guid DepartmentIDField;
        
        private string DepartmentNameField;
        
        private string DepartmentShortNameField;
        
        private string PositionField;
        
        private System.Nullable<System.Guid> PositionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentShortName
        {
            get
            {
                return this.DepartmentShortNameField;
            }
            set
            {
                this.DepartmentShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PositionID
        {
            get
            {
                return this.PositionIDField;
            }
            set
            {
                this.PositionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomizationInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomizationInfoDto : object
    {
        
        private PatientsWcf.CustomSettingsDto CustomSettingsField;
        
        private System.Collections.Generic.List<PatientsWcf.CustomFromDepartmentDto> FromDepartmentsField;
        
        private System.Collections.Generic.List<PatientsWcf.CustomReplacementDoctorDto> ReplacementDoctorField;
        
        private PatientsWcf.WebPagesInfoDto WebPagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.CustomSettingsDto CustomSettings
        {
            get
            {
                return this.CustomSettingsField;
            }
            set
            {
                this.CustomSettingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.CustomFromDepartmentDto> FromDepartments
        {
            get
            {
                return this.FromDepartmentsField;
            }
            set
            {
                this.FromDepartmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.CustomReplacementDoctorDto> ReplacementDoctor
        {
            get
            {
                return this.ReplacementDoctorField;
            }
            set
            {
                this.ReplacementDoctorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.WebPagesInfoDto WebPages
        {
            get
            {
                return this.WebPagesField;
            }
            set
            {
                this.WebPagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomSettingsDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomSettingsDto : object
    {
        
        private System.DateTime DateUpdateField;
        
        private byte MaxPeriodDataField;
        
        private bool OnlineModeField;
        
        private byte PeriodActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MaxPeriodData
        {
            get
            {
                return this.MaxPeriodDataField;
            }
            set
            {
                this.MaxPeriodDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlineMode
        {
            get
            {
                return this.OnlineModeField;
            }
            set
            {
                this.OnlineModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PeriodActive
        {
            get
            {
                return this.PeriodActiveField;
            }
            set
            {
                this.PeriodActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebPagesInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class WebPagesInfoDto : object
    {
        
        private PatientsWcf.CustomPersonDto CustomPersonField;
        
        private System.Collections.Generic.List<PatientsWcf.WebPageInfoDto> WebPageInfosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PatientsWcf.CustomPersonDto CustomPerson
        {
            get
            {
                return this.CustomPersonField;
            }
            set
            {
                this.CustomPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.WebPageInfoDto> WebPageInfos
        {
            get
            {
                return this.WebPageInfosField;
            }
            set
            {
                this.WebPageInfosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFromDepartmentDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomFromDepartmentDto : object
    {
        
        private System.Guid BusinessElementIDField;
        
        private System.DateTime DateUpdateField;
        
        private bool SelectedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BusinessElementID
        {
            get
            {
                return this.BusinessElementIDField;
            }
            set
            {
                this.BusinessElementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected
        {
            get
            {
                return this.SelectedField;
            }
            set
            {
                this.SelectedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomReplacementDoctorDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomReplacementDoctorDto : object
    {
        
        private System.DateTime DateUpdateField;
        
        private System.Guid PersonIdField;
        
        private System.Guid PositionTypeIDField;
        
        private bool SelectedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PositionTypeID
        {
            get
            {
                return this.PositionTypeIDField;
            }
            set
            {
                this.PositionTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected
        {
            get
            {
                return this.SelectedField;
            }
            set
            {
                this.SelectedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomPersonDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomPersonDto : object
    {
        
        private System.Collections.Generic.List<PatientsWcf.CustomGridPersonDto> CustomGridPersonField;
        
        private System.Collections.Generic.List<PatientsWcf.CustomGroupPersonsDto> CustomGroupPersonsField;
        
        private System.DateTime DateUpdateField;
        
        private string FormIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.CustomGridPersonDto> CustomGridPerson
        {
            get
            {
                return this.CustomGridPersonField;
            }
            set
            {
                this.CustomGridPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PatientsWcf.CustomGroupPersonsDto> CustomGroupPersons
        {
            get
            {
                return this.CustomGroupPersonsField;
            }
            set
            {
                this.CustomGroupPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormId
        {
            get
            {
                return this.FormIdField;
            }
            set
            {
                this.FormIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebPageInfoDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class WebPageInfoDto : object
    {
        
        private System.DateTime DateUpdateField;
        
        private string FormIdField;
        
        private string FormNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormId
        {
            get
            {
                return this.FormIdField;
            }
            set
            {
                this.FormIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName
        {
            get
            {
                return this.FormNameField;
            }
            set
            {
                this.FormNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomGridPersonDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomGridPersonDto : object
    {
        
        private bool AvailableGroupingsField;
        
        private string NameColumnEnField;
        
        private string NameColumnRuField;
        
        private bool OrderColumnField;
        
        private bool VisibilityColumnField;
        
        private bool isGroupingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AvailableGroupings
        {
            get
            {
                return this.AvailableGroupingsField;
            }
            set
            {
                this.AvailableGroupingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameColumnEn
        {
            get
            {
                return this.NameColumnEnField;
            }
            set
            {
                this.NameColumnEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameColumnRu
        {
            get
            {
                return this.NameColumnRuField;
            }
            set
            {
                this.NameColumnRuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OrderColumn
        {
            get
            {
                return this.OrderColumnField;
            }
            set
            {
                this.OrderColumnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisibilityColumn
        {
            get
            {
                return this.VisibilityColumnField;
            }
            set
            {
                this.VisibilityColumnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isGrouping
        {
            get
            {
                return this.isGroupingField;
            }
            set
            {
                this.isGroupingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomGroupPersonsDto", Namespace="http://schemas.datacontract.org/2004/07/InpatientDoctorApp.Dto")]
    public partial class CustomGroupPersonsDto : object
    {
        
        private bool OrderButtonField;
        
        private bool SelectedField;
        
        private string nameButtonEnField;
        
        private string nameButtonRuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OrderButton
        {
            get
            {
                return this.OrderButtonField;
            }
            set
            {
                this.OrderButtonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected
        {
            get
            {
                return this.SelectedField;
            }
            set
            {
                this.SelectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameButtonEn
        {
            get
            {
                return this.nameButtonEnField;
            }
            set
            {
                this.nameButtonEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameButtonRu
        {
            get
            {
                return this.nameButtonRuField;
            }
            set
            {
                this.nameButtonRuField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientsWcf.IInpatientDoctor")]
    public interface IInpatientDoctor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetPatients", ReplyAction="http://tempuri.org/IInpatientDoctor/GetPatientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.PatientDto>> GetPatientsAsync(PatientsWcf.PersonQueryParamsDto personQueryParamsDto, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetIndicant", ReplyAction="http://tempuri.org/IInpatientDoctor/GetIndicantResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetIndicantAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/Authorize", ReplyAction="http://tempuri.org/IInpatientDoctor/AuthorizeResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.Guid>> AuthorizeAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetAllActualDoctors", ReplyAction="http://tempuri.org/IInpatientDoctor/GetAllActualDoctorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.ActualDoctorDto>> GetAllActualDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetAllDepartments", ReplyAction="http://tempuri.org/IInpatientDoctor/GetAllDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.DepartmentDto>> GetAllDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetUserInfo", ReplyAction="http://tempuri.org/IInpatientDoctor/GetUserInfoResponse")]
        System.Threading.Tasks.Task<PatientsWcf.UserInfoDto> GetUserInfoAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetCustomization", ReplyAction="http://tempuri.org/IInpatientDoctor/GetCustomizationResponse")]
        System.Threading.Tasks.Task<PatientsWcf.CustomizationInfoDto> GetCustomizationAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/SaveCustomization", ReplyAction="http://tempuri.org/IInpatientDoctor/SaveCustomizationResponse")]
        System.Threading.Tasks.Task<bool> SaveCustomizationAsync(PatientsWcf.CustomizationInfoDto customInfoDto, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInpatientDoctor/GetHealthcareIndicants", ReplyAction="http://tempuri.org/IInpatientDoctor/GetHealthcareIndicantsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetHealthcareIndicantsAsync(System.Guid id, double days);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IInpatientDoctorChannel : PatientsWcf.IInpatientDoctor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InpatientDoctorClient : System.ServiceModel.ClientBase<PatientsWcf.IInpatientDoctor>, PatientsWcf.IInpatientDoctor
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InpatientDoctorClient() : 
                base(InpatientDoctorClient.GetDefaultBinding(), InpatientDoctorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IInpatientDoctor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), InpatientDoctorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InpatientDoctorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InpatientDoctorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.PatientDto>> GetPatientsAsync(PatientsWcf.PersonQueryParamsDto personQueryParamsDto, string login)
        {
            return base.Channel.GetPatientsAsync(personQueryParamsDto, login);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetIndicantAsync(System.Guid id)
        {
            return base.Channel.GetIndicantAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.Guid>> AuthorizeAsync(string login, string password)
        {
            return base.Channel.AuthorizeAsync(login, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.ActualDoctorDto>> GetAllActualDoctorsAsync()
        {
            return base.Channel.GetAllActualDoctorsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.DepartmentDto>> GetAllDepartmentsAsync()
        {
            return base.Channel.GetAllDepartmentsAsync();
        }
        
        public System.Threading.Tasks.Task<PatientsWcf.UserInfoDto> GetUserInfoAsync(string login)
        {
            return base.Channel.GetUserInfoAsync(login);
        }
        
        public System.Threading.Tasks.Task<PatientsWcf.CustomizationInfoDto> GetCustomizationAsync(string login)
        {
            return base.Channel.GetCustomizationAsync(login);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCustomizationAsync(PatientsWcf.CustomizationInfoDto customInfoDto, string login)
        {
            return base.Channel.SaveCustomizationAsync(customInfoDto, login);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PatientsWcf.IndicantDto>> GetHealthcareIndicantsAsync(System.Guid id, double days)
        {
            return base.Channel.GetHealthcareIndicantsAsync(id, days);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInpatientDoctor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInpatientDoctor))
            {
                return new System.ServiceModel.EndpointAddress("http://95.161.3.172:666/Doctest/");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InpatientDoctorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IInpatientDoctor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InpatientDoctorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IInpatientDoctor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IInpatientDoctor,
        }
    }
}
